### ISSUE TITLE
Is this the official location of this package?

### ISSUE THREAD

**Issue by MorganJamesSmith** [stardiviner/org-contacts.el#2]
Is this the official location of this package?

If so it should be removed from org contrib (https://git.sr.ht/~bzg/org-contrib) and the link should be updated on this page: https://orgmode.org/worg/org-contrib/

I bring up this issue because I'd like to put this updated version in the GNU Guix package manager where I get all my other Emacs packages. You don't have to worry about that though, I'll do it if I get confirmation that this is the official repo.

It would also be nice to put this package in some other package aggregation places. I'd suggest the new nongnu elpa (https://elpa.nongnu.org/nongnu/). You might even be able to get some help doing that if you contact this fellow as they've been doing it for others: https://ruzkuku.com/files/nongnu-work.html

**Comment by stardiviner** [comment]
Yes, currently I maintain this package. Org-contrib start to suggest maintainer separating packages.

I will consider NonGNU ELPA. Thanks for suggestion.

**Comment by MorganJamesSmith** [comment]
org-contacts is now in the GNU Guix package manager: https://issues.guix.gnu.org/51499.

When creating the package I had to write a synopsis and description.  Feel free to use these however you feel.  It might be nice to add them to the readme.


synopsis: Contacts management system for Org mode

description: Manage your contacts from Org mode.  You can auto complete email addresses, export contacts to a vCard file, put birthdays in your Org Agenda, and more.

**Comment by stardiviner** [comment]
Thanks, advice token and updated to README.
